export let modelData = [
  {
    modalName: "Aberal James",
    rating: 4,
    filename: "aberal_james.jpg",
    gender: "male",
  },
  {
    modalName: "Afaella",
    rating: 4.5,
    filename: "afaella.jpg",
    gender: "female",
  },
  {
    modalName: "Aimmy",
    rating: 3,
    filename: "aimmy.jpg",
    gender: "female",
  },
  {
    modalName: "Ammar",
    rating: 3,
    filename: "ammar.jpg",
    gender: "female",
  },
  {
    modalName: "Arther",
    rating: 3,
    filename: "arther.jpg",
    gender: "male",
  },
  {
    modalName: "Austin",
    rating: 3.5,
    filename: "austin.jpg",
    gender: "male",
  },
  {
    modalName: "Brody",
    rating: 5,
    filename: "brody.jpg",
    gender: "male",
  },
  {
    modalName: "Fabio",
    rating: 3,
    filename: "fabio.jpg",
    gender: "male",
  },
  {
    modalName: "Hanson",
    rating: 3,
    filename: "hanson.jpg",
    gender: "male",
  },
  {
    modalName: "James",
    rating: 4,
    filename: "James.jpg",
    gender: "female",
  },
  {
    modalName: "Jhon",
    rating: 3,
    filename: "jhon.jpg",
    gender: "male",
  },
  {
    modalName: "Jhonson",
    rating: 4.5,
    filename: "jhonson.jpg",
    gender: "male",
  },
  {
    modalName: "layla",
    rating: 4.5,
    filename: "layla.jpg",
    gender: "female",
  },
  {
    modalName: "Loly James",
    rating: 3.5,
    filename: "lolyJames.jpg",
    gender: "female",
  },
  {
    modalName: "Mark",
    rating: 3,
    filename: "mark.jpg",
    gender: "male",
  },
  {
    modalName: "Mike",
    rating: 5,
    filename: "mike.jpg",
    gender: "male",
  },
  {
    modalName: "Reffla",
    rating: 5,
    filename: "reffla.jpg",
    gender: "female",
  },
  {
    modalName: "Rose Marry",
    rating: 3,
    filename: "rose_marry.jpg",
    gender: "female",
  },
];
